### ISSUE TITLE
SJISの文字コードが入ったファイルがASCIIと判定されます

### ISSUE THREAD

**Issue by cxxxr** [t-sin/inquisitor#17]
指定したファイルはhttps://raw.githubusercontent.com/xyzzy-022/xyzzy/develop/lisp/winhelp.l

```
(with-open-file (in "winhelp.l"
                    :element-type '(unsigned-byte 8))
  (inquisitor:detect-encoding in :jp)) 
=> :UTF-8
```

**Comment by cxxxr** [comment]
*detecting-buffer-size*を大きめにすると正しく判定されました

**Comment by t-sin** [comment]
デフォルトの_detecting-buffer-size_より先にASCII以外の(UTF-8以外とされるような)文字があるケースですね。_detecting-buffer-size_自体あまりよろしくないですよね…。

**Comment by t-sin** [comment]
APIの整理が急務だと思っていて、その一環としてstreamやpathnameに対してはバッファサイズをoptionalに指定できるようにするつもりです。

**Comment by cxxxr** [comment]
ありがとうございます
APIに関してそういう変更をしようとフォークしたんですが
英語が書けずコミットが終わりません

**Comment by cxxxr** [comment]
そういえばdetect-end-of-lineは改行コードが見つかるまで走査すればいいのなら*detecting-buffer-size*は必要ありませんね

それからベクタを一度だけ作ってその中で見ていくのはファイル全体を見ようとしたら
ベクタが大きくなりすぎるのが気になります
ある程度の大きさのベクタにその大きさ分だけデータを入れて見ていく動作を繰り返せたら良さそうです

**Comment by t-sin** [comment]
確かに確かに。
そもそも`*detecting-buffer-size*`なんて不要で、バッファサイズは引数で指定できるようにしたほうが、このissueのようなケースに対しては（全体としても）いいかなと思っていました。
具体的には
1. `*detecting-buffer-size*`は消す
2. `detect-encoding`と`detect-end-of-line`(名前短くしたい)をメソッドに
   - `detect-external-format`と同じくベクタ、ストリーム、パスネームに対応
3. ストリーム/ファイルに対してはバッファサイズを`&optional`で指定できるように
   - `detect-`系メソッド全てに対してやる
   - もしファイル全体をチェックしてほしかったら`:full`でも渡すとか

のような感じで。

メソッドにも`&optional`とか使えるようなので([HyperSpec: defmethod](http://www.lispworks.com/documentation/lw70/CLHS/Body/m_defmet.htm))、pull requestをマージしたあとでそのような対応をしようかなと考えています。

結果として`detect-external-format-from-file`は消すことになると思いますが、そのほうがスッキリしてていいのかな、と。

**Comment by cxxxr** [comment]
いいですね
`detect-external-format-from-file`は自分で書いといてなんですがあまり良いものではないと思います

**Comment by t-sin** [comment]
あっ。
- ベクタを大きくせず使い回す

を忘れるところでした。

別でAPI整理のissue立てようかな…。

**Comment by cxxxr** [comment]
別のissueにしたほうが良さそうですね

**Comment by t-sin** [comment]
別issue(#22)にしたのでクローズします。
