### ISSUE TITLE
改行コードがcrlfだとsbclでread-lineの末尾にcrが紛れる問題

### ISSUE THREAD

**Issue by cxxxr** [t-sin/inquisitor#20]
ライブラリを使う側でsbclとその他に分けて
sbclならread-lineで得た文字列の末尾を除去しないといけません
これはinquisitor側でした方がいいと思います

ひとつめはwith-open-fileをinquisitor側でサポートしてgray-streamsを使う方法を考えました
このやり方だと万事うまくいきそうですがsbclのcrlfのためだけにこれをするのは冗長で実装が面倒です

ふたつめはwith-open-fileと一緒にdo-read-lineもinquisitor側でサポートします

```
(with-input-file ((in external-format) path ...)
  (do-read-line ((string eof-p) in external-format)
    ...))
```

こうすると末尾のcrの除去を裏に隠せます

変数external-formatを明示的に書いた理由は
ライブラリを使う側でファイルの保存時に文字コードを保つために必要だからです
sbclなら改行コードも考慮する必要があるのでふたつ目の方法だとdo-print-line
ひとつ目の方法だと定義したstreamクラスのスロットににencodingとend-of-lineを入れておく必要があります

**Comment by cxxxr** [comment]
external-formatで改行コードも覚えておく必要があるので
encodingとend-of-lineを入れた構造体か何かが良さそうです

**Comment by cxxxr** [comment]
長々と書きましたがflexi-streamsをinquisitorと一緒に使えばいいだけですね
失礼しました

**Comment by t-sin** [comment]
SBCLの改行コード扱えない問題はやっかいですよね。

でもinquisitorでそこまで(`do-read-line`関数を追加)する必要はないかなと考えてます。
ただし、flexi-streamsやbabelなんかのexternal-formatはinquisitorで九州する(=文字コードに関してはinquisitorが名前を一挙に引き受ける)べきだと考えています。

`do-read-line`的な関数を追加しない理由は2点で
- そこまでするなら`cl`パッケージのread系を捨て置けない
- 他の改行コードを扱えない処理系(あるのかは知りませんが…)をサポートするとき、SBCLと同じ轍を踏むことになる

からです。

その点はflexi-streamとの併用でなんとかするということなので、このissue自体はクローズしてしまってもいいでしょうか？

flexi-streamsなどのexternal-formatの吸収は、inquisitorでやるべきだと考えてます。
issueに挙げたつもりだったんですが忘れてました（思い出せてよかった）。

Inquisitorで、人が処理系差やライブラリ差に悩まされることのないようにしたい、という方針があるんです（脳内に）。
external-formatを独自に持ってるライブラリってもう登場しないと思ってて、flexi-streamsとbabelだけだと思ってるので、これくらいならいいかな、と。

どうやって抽象化&提供するかは悩んでますが、issueにあげておきます。

**Comment by cxxxr** [comment]
確かにdo-read-lineは中途半端ですね

それとさっきのコメントを書いた後で気付いんたんですがflexi-streamsではshift-jisもeuc-jpも対応してないんですね
なのでflexi-streamsと併用することは出来ずinquisitor側でどうにかしないとならないんです
そうするとgray streamsを定義するのが一番処理系の差を吸収出来ると思います
そこでexternal-formatも扱えばうまく行きそうです

とりあえず今のところはライブラリを使う側で改行コードの判別をするやり方にしておきます

**Comment by t-sin** [comment]
うわあ、ほんとだflexi-streams…。というか[win32:codepageが使えるのがLispWorks for Windowsのみ](http://weitz.de/flexi-streams/#external-formats)というだけでも不安しかない…。コードページと言ってもどのコードページなのかも謎ですが。Shift JISもどきのCP932なのか、何なのか。

External-formatの丸めこみは、inquisitorで責任を持ちます。
だけど、うーん、inquisitor.streamパッケージ誕生かな…？

babelのbabel-streamsでなんとかなりませんかね。ぼくは使ったことがないのでまだなんとも言えませんが…。

**Comment by t-sin** [comment]
WindowsのコードページについてはちゃんとID指定するって書いてありました。よく見てなかった…。

>  a couple of Windows code pages (denoted by the keyword :CODE-PAGE and an obligatory :ID argument)
> http://weitz.de/flexi-streams/#external-formats

**Comment by t-sin** [comment]
@cxxxr このissue完全放置してましたが、解決しましたでしょうか。

**Comment by cxxxr** [comment]
masterで試してみましたがsbclではcrはまだ残っています

**Comment by cxxxr** [comment]
quickloadから入れた古いものが優先されてて間違ってました
すみません

もう一度masterでやると`inquisitor.encoding.guess::guess-jp`でエラーが出ます

```
(defparameter x
  #(140 246 147 73 130 200 145 123 141 245 140 87 129 65 146 178 141 184 138 175
    130 170 130 162 130 233 129 66 10 130 237 130 189 130 181 130 205 148 222 130
    231 130 170 148 67 150 177 130 240 144 139 141 115 130 181 130 196 130 162
    130 233 130 198 130 177 130 235 130 240 140 169 130 189 129 66))

(inquisitor:detect-external-format x :jp)
```

**Comment by cxxxr** [comment]
エラーが起こる原因はguess-jp内のgenerator-orderマクロで生成するorderに見えます

orderのそれぞれのdfaでdfa-nameがeuc-jpとcp932のときのarcsがnilなのに
dfa-processとその下で使われるdfa-nextで配列として使われています

とりあえずdfa-processのdfa-aliveの前にarcsがnilではないかを確認すればうまく動きました

**Comment by cxxxr** [comment]
sbclの問題は有耶無耶にしてとりあえず解決したということでいいんですが
このissueは閉じたほうがいいんですかね

**Comment by t-sin** [comment]
おお、エンコーディング判定部のバグがあったのですね…。ご指摘ありがとうございます。これは、別issueで対応します。

ちなみにSBCLのCR入っちゃう問題については
- SBCLだけが改行コードを扱えないことが要因
- Inquisitorはあくまでも文字コード判定器

だと思っているので、inquisitorでは対応しません。

というわけで、このissueはいったんクローズしたいなあと思っています。

**Comment by t-sin** [comment]
SBCLの問題は僕もちょっと酷いと思っているので、SBCLに改行コードを扱えるようにするパッチを投げるか、SBCL対策のライブラリを別につくるか、策を講じたいところなんですが、まだ手がまわらなさそうです。

**Comment by cxxxr** [comment]
gray-streamsで包めば簡単にできそうですがそんなに甘くないんですかね
このissueは閉じます
