### ISSUE TITLE
detect-end-of-lineが常にnilを返します

### ISSUE THREAD

**Issue by cxxxr** [t-sin/inquisitor#26]
Common Lispのloopマクロ

```
(loop for i from 1 to 3
         with j = i
         collect (list i j))
```

`with j = i`はループ毎に更新されるのではなく最初に一回だけなので
結果は`((1 1) (2 2) (3 3))`ではなく`((1 1) (2 1) (3 1))`です

detect-end-of-lineのloopを見てみると

```
(loop for n = (read-sequence vec stream) ; ここでバッファ変数vecを更新して
         with eol = (eol-guess-from-vector vec) ; ここで前の行のvecではなく空のバッファのvecを使ってeolには常にnilが入る
         until (or (zerop n)
                      (not (null eol))) ; eolは常にnilなので(not (null eol))は常にnilでloopを抜ける
         finally (return eol))
```

この結果detect-end-of-lineは常にnilを返します

このloopのwithをforに変えて動かすと正しく動くはずなんですがテストが通りません
テストの失敗した部分を見てみると  
× :LF is expected to be NIL 
となっています
しかしこれは:LFが正しいはずなんです

他の場所でも
:UCS-2LE is expected to be :UTF-16BE や
:BIG5 is expected to be :ISO-2022-TW がありますが
これもdetect-end-of-lineの結果を引きずってるみたいです

常にnilを返すバグを無視してテストのほうを変えて動くようにしてるように見えます
この機能は都合が悪くてわざと一時的に動かないようにしてるんでしょうか

気が向いたら直しておいてほしいです

**Comment by t-sin** [comment]
おお…。ご指摘ありがとうございます。

> ``` lisp
> (loop for n = (read-sequence vec stream) ; ここでバッファ変数vecを更新して
>          with eol = (eol-guess-from-vector vec) ; ここで前の行のvecではなく空のバッファのvecを使ってeolには常にnilが入る
>          until (or (zerop n)
> ```

これはその通りですね。気付けずに首をずっと傾げてた部分でした。
#25 はacceptします。

---

パスしないテストというと

``` lisp
 If file has no newline then return NIL
    × :LF is expected to be NIL  ; ←これ
    ✓ NIL is expected to be NIL 
```

ですかね…？

これ、関数でいうと`detect-end-of-line`じゃなくて`eol-quess-from-vector`のテストなんです。
ファイルが改行を含まないときは`nil`を返そうと決意して、そう実装したらでてきたバグ(#23)で、いまいち原因がわかっていません。

こいつが足を引っぱりまくっているのは事実なので、すぐに対処します。

#25 はマージしますが、このissueはまだ開いたままにしておきます。

**Comment by cxxxr** [comment]
#23ですがnilではなく:lfを返すのはファイルの末尾に改行があるから正しいと思います

**Comment by t-sin** [comment]
はい。すみません。しっかりとLFついてますね。

テストコードが悪いです。テストコードの追加・修正した上で、クローズとします。

**Comment by t-sin** [comment]
e40955aで正しいテスケースを追加しました。一旦クローズします。

**Comment by cxxxr** [comment]
ありがとうございます
