### ISSUE TITLE
guess-jp causes error

### ISSUE THREAD

**Issue by t-sin** [t-sin/inquisitor#27]
This code causes an error at `inquisitor.encoding.guess::guess-jp`: 

> ``` lisp
> (defparameter x
>  #(140 246 147 73 130 200 145 123 141 245 140 87 129 65 146 178 141 184 138 175
>     130 170 130 162 130 233 129 66 10 130 237 130 189 130 181 130 205 148 222 130
>    231 130 170 148 67 150 177 130 240 144 139 141 115 130 181 130 196 130 162
>    130 233 130 198 130 177 130 235 130 240 140 169 130 189 129 66))
> 
> (inquisitor:detect-external-format x :jp)
> ```

**Comment by cxxxr** [comment]
table.lispのdefine-dfaではsjisやeucjと定義されていますがguess-jp内のgenerate-orderではcp932やeuc-jpとなっていてgenerate-order内のfind-symbolが失敗しているように見えます

**Comment by t-sin** [comment]
うわあ。名前を変えたときのミスでした…。直します。
