### ISSUE TITLE
Inquisitor-flexi not build in recent SBCL

### ISSUE THREAD

**Issue by quicklisp** [t-sin/inquisitor#55]
If you use the latest git version of inquisitor, `(ql:quickload "inquisitor-flexi" :verbose t)` does not work in recent SBCLs.

**Comment by t-sin** [comment]
Thank you for reporting. I’ll check it tomorrow.

**Comment by t-sin** [comment]
This is caused by fix about renaming `:ucs-2*` -> `:utf-16*` (https://github.com/t-sin/inquisitor/issues/51), I forgot fixing inquisitor-flexi.

**Comment by t-sin** [comment]
@quicklisp It is fixed at the commit 264314c on `master` branch.
I confirmed that (1) `(ql:quickload :insuisitor-flexi)` succeeded, (2) its test passed.
